<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hao Zhu">
<meta name="dcterms.date" content="2025-03-15">

<title>Paper – PSY5002_HaoZhu</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">PSY5002_HaoZhu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Paper</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">scripts</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Hao Zhu </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 15, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>(Title)</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Human learning hinges on the ability to recognize and interpret predictive cues in the environment. Classic work in associative learning has shown that when two or more cues consistently appear together, their interactions can be competitive—where a dominant cue “blocks” another from acquiring associative strength—or facilitative, in which cues mutually boost each other’s predictive value. These phenomena play a fundamental role not only in understanding how people learn cause-effect relationships but also in broader psychological processes such as selective attention, cognitive inference, and clinical outcomes related to anxiety and stress. In the dissertation by Alhazmi (2022), a series of experiments explored the interplay between these different styles of cue interaction—particularly examining why some individuals tend toward facilitative (or “noncompetitive”) learning while others exhibit more canonical patterns of cue competition. The present paper focuses on Experiment 4 of that work, in which I conducted a detailed data analysis to investigate individual differences in cue interaction style (competitive vs.&nbsp;facilitative) and whether their styles are related to anxiety, depression, and stress measures. By leveraging advanced statistical techniques acquired in my independent research course, I re-examined the data to (add details later).</p>
<p>This introductory section provides an overview of the theoretical basis for cue interaction, including both classical associative models and more contemporary accounts that incorporate higher-order cognitive processes.</p>
<p>Theoretical accounts of cue interaction have historically emphasized how cues compete for associative strength, a process often referred to as “cue competition.” Early associative models (e.g., Bush &amp; Mosteller, 1951, 1955) proposed that the predictive value of any given cue depends solely on its individual correlation with the outcome. This view was challenged by the influential Rescorla-Wagner model (Rescorla &amp; Wagner, 1972), which introduced the concept of a summed prediction error. According to this model, cues presented in compound share a limited pool of associative strength; a cue that is already a strong predictor of an outcome will “block” new cues from acquiring substantial associative strength (Kamin, 1968; Rescorla &amp; Wagner, 1972). Later theories, particularly attentional models (Mackintosh, 1975; Pearce &amp; Hall, 1980), posited that competition stems not just from summed prediction errors but also from changes in the amount of attention allocated to each cue.</p>
<p>However, accumulating evidence suggests that cues can also facilitate one another—rather than compete—under certain circumstances (Bouton et al., 1987; Durlach &amp; Rescorla, 1980). Such “cue facilitation” occurs when the presence of a well-established cue enhances the predictive value of a novel cue (Batsell Jr &amp; Batson, 1999). Models addressing both competition and facilitation often incorporate within-compound associations—that is, direct links formed between cues presented together. In the Sometimes-Competing Retrieval (SOCR) model (Stout &amp; Miller, 2007), these within-compound associations may either suppress or augment responding, depending on a “switching operator” that governs whether indirect cue activation will interfere with or bolster responding. Similarly, Pineño’s (2007) extension of the Rescorla-Wagner model assumes that a cue’s novelty moderates how strongly it draws on within-compound associations for its response—leading sometimes to competition, sometimes to facilitation. These dual-process models thus capture both the classic competitive phenomena and the growing body of evidence for cooperative, or facilitative, interactions among cues.</p>
<p>In addition to these associative mechanisms, propositional and higher-order reasoning can also influence cue interactions. According to propositional accounts, human learners form cognitive inferences about causal relationships, rather than simply accumulating associative strength through trial-by-trial error signals (Mitchell et al., 2009). Thus, learners may explicitly reason that “if Cue A by itself predicts the outcome, and Cue A together with Cue X produces no change in the outcome, then Cue X is not causally relevant,” leading to blocking-like effects (Cheng &amp; Novick, 1990; De Houwer &amp; Beckers, 2003). Higher-order cognition may similarly generate facilitative effects if learners reason that a known predictor could boost the effectiveness of other cues present in the same compound. These propositional processes need not replace traditional associative mechanisms; indeed, both conscious inference and lower-level associative learning may jointly shape how cues compete or facilitate one another under varying task conditions (Mitchell et al., 2009).</p>
<p>Another theoretical perspective on cue interaction revolves around <strong>within-compound associations</strong>, which are direct links formed between cues that are presented simultaneously. Rather than focusing exclusively on how each cue associates with an outcome, this view emphasizes that cues can become associated with each other—sometimes resulting in one cue retrieving the memory of its partner, which in turn activates the representation of the shared outcome (Melchers et al., 2004; Miller &amp; Matzel, 1988). This mechanism can explain why, for instance, reinforcing one element of a compound (A) in a later stage may retrospectively weaken or enhance responses to the other (X), even when X is not explicitly retrained—an effect not easily handled by standard, purely competitive models. Recent formulations, such as Pineño’s (2007) model or the Sometimes-Competing Retrieval (SOCR) model (Stout &amp; Miller, 2007), specifically integrate within-compound associations to account for both <strong>competitive</strong> interactions (when indirect retrieval suppresses responding) and <strong>facilitative</strong> interactions (when indirect retrieval augments responding). By focusing on how cues become interconnected, these approaches help clarify why certain learners show noncompetitive or “excessive” associative patterns that can, in clinical populations, manifest as overgeneralized fear or heightened sensitivity to redundant cues.</p>
<p>Taken together, these perspectives underscore how cue interaction can manifest in both competitive and facilitative patterns, shaped by propositional reasoning as well as by within-compound associations. In the fourth experiment of Alhazmi’s (2022) dissertation, these themes converge in a paradigm specifically designed to capture variability in cue interaction styles under carefully controlled conditions. The next sections detail how I reanalyzed the dataset from this experiment, leveraging advanced statistical methods to explore (1) whether individual shows differences in cue competition or facilitation, and (2) how these differences might correlate with measures of anxiety, depression, and stress.</p>
<p><strong>Description of the Fourth Experiment</strong></p>
<p>Experiment&nbsp;4 was developed to determine how within-compound associations might tilt cue interaction toward competitive or facilitative patterns, and whether these individual tendencies align with varying levels of anxiety, depression, and stress. The experiment utilized a two-stage training procedure—initial training followed by compound trials—culminating in a reversal manipulation that differed between two groups. What follows is a more detailed account of the procedure:</p>
<p><strong>Participants and Design.</strong></p>
<p>Over 400 adults were recruited online (via Prolific) and randomly assigned to one of two groups: Control (no outcome reversal) or Experimental (outcome reversal).</p>
<p>In both groups, each participant was exposed to two cues (A and B) initially reinforced with coins or bomb outcomes, respectively, so that A reliably predicted a positive outcome (coins) while B reliably predicted a negative outcome (bomb).</p>
<p>Stage 1 (Initial Training).</p>
<p>Cues A and B were each presented multiple times (e.g., eight trials per cue). Consistent with the design, Cue A was always followed by the coin outcome, while Cue B was always followed by the bomb outcome. This stage established a baseline expectation that A = coins and B = bomb.</p>
<p>Stage 2 (Compound Training).</p>
<p>Both groups next received extended training over several blocks (e.g., seven blocks). These blocks included the original cues (A→coins, B→bomb) plus newly introduced compound cues:&nbsp; AW (A paired with a novel cue W), 75% resulting in coins and 25% in bombs.</p>
<p>BZ (B paired with a novel cue Z), 25% resulting in coins and 75% in bombs.</p>
<p>AX (A with novel cue X) and BY (B with novel cue Y), each reinforced 50% of the time with coins.</p>
<p>These compound trials tested how novel cues (W, X, Y, Z) might “inherit” more or less coin or bomb expectancy from their better-established partners (A or B). Of particular interest were X and Y, the target cues, since they were paired with opposite outcomes on half the trials and thus could trend toward coins or bombs depending on how participants integrated the companion cue’s history.</p>
<p>Stage 3 (Reversal Manipulation).</p>
<p>At this point, the Experimental group received a reversal of outcomes for Cues A and B (i.e., A became bomb, B became coins), while the Control group continued with the same contingencies (A = coins, B = bomb).</p>
<p>The logic behind this manipulation was to identify whether people who relied on strong within-compound associations (especially for cues X or Y) would update the predictive value of those target cues more drastically than those who did not depend on within-compound links.</p>
<p>Stage 4 (Final Probe Trials).</p>
<p>Both groups completed additional probe trials in which Cues A, B, X, and Y were tested individually without explicit feedback, to assess how much the earlier reversal or continued training influenced each cue’s perceived outcome.</p>
<p><strong>Dependent Variables</strong></p>
<ol type="1">
<li><p><strong>Distance.</strong> A key behavioral measure was how close participants positioned themselves (or their avatar) to the anticipated outcome location on each trial. By standing near the center when they predicted coins (to maximize reward) or retreating toward the edge if they expected a bomb (to avoid penalty), participants generated a continuous “distance” metric that captured their outcome expectations in real time. Shorter distances indicated a higher belief in receiving coins, whereas larger distances pointed to a strong expectation of bombs.</p></li>
<li><p><strong>Ratings.</strong> In addition to the distance measure, participants periodically provided explicit numeric ratings of how likely they believed it was that the cue in question predicted coins (as opposed to bombs). After each trial—or at defined “probe” trials—participants were shown a rating scale (for instance, 0 to 10) and indicated how confident they were that the current cue would lead to a coin outcome. These ratings supplemented the distance data by revealing learners’ conscious expectations about each cue’s predictive value.</p></li>
</ol>
<p><strong>Anxiety, Depression, and Stress Measures.</strong></p>
<p>After the learning task, participants completed the DASS questionnaire (Lovibond, 1995), yielding subscales for depression, anxiety, and stress. These scores were later correlated with each participant’s “cue interaction index” (the degree to which X vs.&nbsp;Y showed competition or facilitation), testing the hypothesis that attenuated competition (i.e., facilitation) might be linked to higher clinical-risk traits such as anxiety or chronic stress.</p>
</section>
<section id="data-analysis" class="level1">
<h1>Data Analysis</h1>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<p>Load data and packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'tidyverse'</span>)) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># install.packages('tidyverse')</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'tidyr'</span>)) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#install.packages('tidyr'); </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyr)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'ggplot2'</span>)) {</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#install.packages('ggplot2'); </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">'gridExtra'</span>)) {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#install.packages('gridExtra'); </span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(gridExtra)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gridExtra

Attaching package: 'gridExtra'

The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("car")</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("effectsize")</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("afex")</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4
Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

************
Welcome to afex. For support visit: http://afex.singmann.science/
- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************

Attaching package: 'afex'

The following object is masked from 'package:lme4':

    lmer</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("emmeans")</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
</div>
<p>Import Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df_game <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'../../data/exp4-raw.csv'</span>, <span class="at">show_col_types=</span><span class="cn">FALSE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df_quest <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'../../data/exp4-raw-quest.csv'</span>, <span class="at">show_col_types=</span><span class="cn">FALSE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>df_attention <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'../../data/exp4-attention.csv'</span>, <span class="at">show_col_types=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We used many filters to exclude bad data - Here is the data from the platform itself. Either people who did not complete the whole thing, or they were too fast for their data to be meaningful, or they skipped all the ratings/probes, all kinds of reasons.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bads <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'594fa525f61b8e00016af178'</span>, <span class="st">'5a90460d1eda41000135f918'</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">'5de301515253b03390043d12'</span>, <span class="st">'5e87ade2da382941f3f1a621'</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">'5ed377271691ea000c548cb0'</span>, <span class="st">'5f3e8506cb479c0a96cf4aac'</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>       <span class="st">'5f8f95862a4ed820d9b071ac'</span>, <span class="st">'60b671ce563975c4907b9c04'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>df_game <span class="ot">=</span> df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>subjectID <span class="sc">%in%</span> bads)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also have participants complete a survey called DAAS in which they answer a couple of questions and then we extract their depression, anxiety and stress scores. As you can see, we have these dimensions mapped to questions and in the following code we just add up all the scores in each dimension.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the question categories</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>depression <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">16</span>, <span class="dv">17</span>, <span class="dv">21</span>, <span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">31</span>, <span class="dv">34</span>, <span class="dv">37</span>, <span class="dv">38</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>anxiety <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">15</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">23</span>, <span class="dv">25</span>, <span class="dv">28</span>, <span class="dv">30</span>, <span class="dv">36</span>, <span class="dv">40</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>stress <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">18</span>, <span class="dv">22</span>, <span class="dv">27</span>, <span class="dv">29</span>, <span class="dv">32</span>, <span class="dv">33</span>, <span class="dv">35</span>, <span class="dv">39</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create column names for each category</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>depression_cols <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'DASS_'</span>, depression)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>anxiety_cols <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'DASS_'</span>, anxiety)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>stress_cols <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'DASS_'</span>, stress)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum the columns for each category and add to df_quest</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>df_quest <span class="ot">&lt;-</span> df_quest <span class="sc">%&gt;%</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">depression =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">all_of</span>(depression_cols)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">anxiety =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">all_of</span>(anxiety_cols)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">stress =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">all_of</span>(stress_cols)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop columns that start with 'DASS'</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>df_quest <span class="ot">&lt;-</span> df_quest <span class="sc">%&gt;%</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">'DASS'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># focus on probe data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="ot">&lt;-</span> df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(outcome <span class="sc">==</span> <span class="st">'probe'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check invalid ratings</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(probeAns<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">|</span> probeAns<span class="sc">&gt;</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subjectID) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 1
# ℹ 1 variable: subjectID &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can use this to filter out those who have lots of missing ratings..</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> df_prp_raw <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subjectID) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">missing =</span> <span class="fu">mean</span>(<span class="fu">is.na</span>(probeAns))) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(missing))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(missing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  subjectID                missing
  &lt;chr&gt;                      &lt;dbl&gt;
1 5c8d12309d2bff0019b4054a  0.977 
2 5c2fcd716ea6880001dc8e3d  0.932 
3 5ce031fc7f65ee001a985a6b  0.932 
4 5f3ec6221b5af3158bc86acd  0.5   
5 5fca97a4b105427256733533  0.159 
6 5915e5c6405db80001f30ff1  0.0682</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># here we also have issues with invalid ratings and we want to know how many bad data out there</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>invalidRatings <span class="ot">&lt;-</span> missing <span class="sc">%&gt;%</span> <span class="fu">filter</span>(missing <span class="sc">&gt;=</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(subjectID)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(subjectID <span class="sc">%in%</span> invalidRatings) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(subjectID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  group            n
  &lt;chr&gt;        &lt;int&gt;
1 control          3
2 experimental     1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter them out...</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_game <span class="ot">&lt;-</span> df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>subjectID <span class="sc">%in%</span> invalidRatings)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="ot">&lt;-</span> df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(outcome <span class="sc">==</span> <span class="st">'probe'</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(df_prp_raw<span class="sc">$</span>subjectID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 393</code></pre>
</div>
</div>
<p>How many participants in each group?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(subjectID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  group            n
  &lt;chr&gt;        &lt;int&gt;
1 control        203
2 experimental   190</code></pre>
</div>
</div>
</section>
<section id="start-of-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="start-of-the-analysis">Start of the analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#df_trn_raw &lt;- df_game %&gt;% filter(outcome != 'probe')</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df_prp_raw <span class="ot">&lt;-</span> df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(outcome <span class="sc">==</span> <span class="st">'probe'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We want to use an average of pre reversal and post reversal. We select 6, 7,8 for pre-reversal baseline and 10,11,12 for post reversal. Note that we also have 6 but we skip it because participant see ratings for first time and they are figuring it out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df_prp_focus <span class="ot">&lt;-</span> df_prp_raw <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rep <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rep =</span> dplyr<span class="sc">::</span><span class="fu">recode</span>(<span class="fu">as.numeric</span>(rep),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">`</span><span class="at">6</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'before'</span>, <span class="st">`</span><span class="at">7</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'before'</span>, <span class="st">`</span><span class="at">8</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'before'</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">`</span><span class="at">10</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'after'</span>, <span class="st">`</span><span class="at">11</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'after'</span>, <span class="st">`</span><span class="at">12</span><span class="st">`</span> <span class="ot">=</span> <span class="st">'after'</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>df_prp <span class="ot">&lt;-</span> df_prp_focus <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subjectID, cue, rep) <span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">probeAns =</span> <span class="fu">mean</span>(probeAns, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">distance =</span> <span class="fu">mean</span>(distance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_prp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  subjectID                cue   rep    probeAns distance
  &lt;chr&gt;                    &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 55acde7cfdf99b28fb8d7e44 A     after  1            84.3
2 55acde7cfdf99b28fb8d7e44 A     before 0.998       119. 
3 55acde7cfdf99b28fb8d7e44 AW    before 0.0882      581  
4 55acde7cfdf99b28fb8d7e44 AX    before 0.411       306  
5 55acde7cfdf99b28fb8d7e44 B     after  0.000952    571  
6 55acde7cfdf99b28fb8d7e44 B     before 0           589. </code></pre>
</div>
</div>
</section>
<section id="stimulus" class="level2">
<h2 class="anchored" data-anchor-id="stimulus">Stimulus</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># shapes and sounds</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># symbol should be unique for each subject and cue</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>df_prp_focus <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( cue <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subjectID, cue) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">ns =</span> <span class="fu">n_distinct</span>(shape), <span class="at">nd =</span> <span class="fu">n_distinct</span>(sound), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( ns <span class="sc">&gt;</span> <span class="dv">1</span> <span class="sc">|</span> nd <span class="sc">&gt;</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: subjectID &lt;chr&gt;, cue &lt;chr&gt;, ns &lt;int&gt;, nd &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df_stimuls <span class="ot">&lt;-</span> df_prp_focus <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( cue <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subjectID, cue) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">shape =</span> <span class="fu">first</span>(shape), <span class="at">sound =</span> <span class="fu">first</span>(sound), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">stimulus_type =</span> <span class="fu">case_when</span>(shape <span class="sc">==</span> <span class="st">'empty'</span> <span class="sc">~</span> <span class="st">'sound'</span>, <span class="at">.default =</span> <span class="st">'shape'</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">stimulus =</span> <span class="fu">case_when</span>(stimulus_type <span class="sc">==</span> <span class="st">'sound'</span> <span class="sc">~</span> sound, <span class="at">.default =</span> shape)) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> cue, <span class="at">values_from =</span> <span class="fu">c</span>(stimulus_type, stimulus), <span class="at">id_cols =</span> subjectID, <span class="at">names_prefix =</span> <span class="st">''</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">stimulus_type_X_Y =</span> <span class="fu">paste</span>(stimulus_type_X, stimulus_type_Y, <span class="at">sep =</span> <span class="st">"_"</span>),</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">stimulus_X_Y =</span> <span class="fu">paste</span>(stimulus_X, stimulus_Y, <span class="at">sep =</span> <span class="st">"_"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="transform" class="level2">
<h2 class="anchored" data-anchor-id="transform">Transform</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># some magic to pivot from long to wide (easier for analysis)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>df_prp_ratings_wide <span class="ot">&lt;-</span> df_prp <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> cue, <span class="at">values_from =</span> probeAns, <span class="at">id_cols =</span> <span class="fu">c</span>(subjectID, rep))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>df_prp_distance_wide <span class="ot">&lt;-</span> df_prp <span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> cue, <span class="at">values_from =</span> distance, <span class="at">id_cols =</span> <span class="fu">c</span>(subjectID, rep))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>df_prp_ratings_wide <span class="ot">&lt;-</span> df_prp_ratings_wide <span class="sc">%&gt;%</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> rep,        </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> <span class="sc">-</span><span class="fu">c</span>(subjectID, rep), </span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_sep =</span> <span class="st">"_"</span>           </span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">'AW_after'</span>, <span class="st">'AX_after'</span>, <span class="st">'BY_after'</span>, <span class="st">'BZ_after'</span>, <span class="st">'W_after'</span>, <span class="st">'Z_after'</span>))</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>df_prp_distance_wide <span class="ot">&lt;-</span> df_prp_distance_wide <span class="sc">%&gt;%</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> rep,</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> <span class="sc">-</span><span class="fu">c</span>(subjectID, rep),</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_sep =</span> <span class="st">"_"</span>      </span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">'AW_after'</span>, <span class="st">'AX_after'</span>, <span class="st">'BY_after'</span>, <span class="st">'BZ_after'</span>, <span class="st">'W_after'</span>, <span class="st">'Z_after'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge the two dataframes</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_ratings_wide <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_prp_distance_wide, <span class="at">by =</span> <span class="st">"subjectID"</span>, <span class="at">suffix =</span> <span class="fu">c</span>(<span class="st">'_rating'</span>, <span class="st">'_dist'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We merge because we can get all information now including group and scores…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_quest, <span class="at">by =</span> <span class="st">"subjectID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#left_join(df_attention, by = "subjectID") %&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_game <span class="sc">%&gt;%</span> <span class="fu">filter</span>(outcome <span class="sc">==</span> <span class="st">'probe'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(subjectID, group) <span class="sc">%&gt;%</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">distinct</span>(), <span class="at">by =</span> <span class="st">"subjectID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_stimuls <span class="sc">%&gt;%</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(subjectID, stimulus_type_X_Y, stimulus_X_Y), <span class="at">by =</span> <span class="st">"subjectID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Filter out the participants who did not rating the stimuli in a meaningful way</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span> <span class="fu">filter</span>(A_before_rating <span class="sc">&gt;</span> B_before_rating, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                                      A_before_rating <span class="sc">&gt;</span> AW_before_rating,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                                      AW_before_rating <span class="sc">&lt;</span> BZ_before_rating, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                                      B_before_rating <span class="sc">&lt;</span> BZ_before_rating,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                                      )</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span> <span class="fu">filter</span>(W_before_rating <span class="sc">&lt;</span> Z_before_rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(subjectID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  group            n
  &lt;chr&gt;        &lt;int&gt;
1 control        172
2 experimental   143</code></pre>
</div>
</div>
</section>
<section id="normalized-index" class="level2">
<h2 class="anchored" data-anchor-id="normalized-index">Normalized Index</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ICI_Norm <span class="ot">&lt;-</span> <span class="cf">function</span>(Y, X) (Y <span class="sc">-</span> X) <span class="sc">/</span> <span class="fu">sqrt</span>(Y<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> X<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ICI_YX_rating_pre_norm =</span> <span class="fu">ICI_Norm</span>(Y_before_rating, X_before_rating),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ICI_YX_dist_pre_norm =</span> <span class="sc">-</span> <span class="fu">ICI_Norm</span>(Y_before_dist, X_before_dist),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ICI_YX_rating_post_norm =</span> <span class="fu">ICI_Norm</span>(Y_after_rating, X_after_rating),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ICI_YX_dist_post_norm =</span> <span class="sc">-</span> <span class="fu">ICI_Norm</span>(Y_after_dist, X_after_dist),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">post_pre_Rating_norm =</span> ICI_YX_rating_post_norm <span class="sc">-</span> ICI_YX_rating_pre_norm,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">post_pre_Dist_norm =</span> ICI_YX_dist_post_norm <span class="sc">-</span> ICI_YX_dist_pre_norm)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ICI_WZ_rating_pre_norm =</span> <span class="fu">ICI_Norm</span>(W_before_rating, Z_before_rating),</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">ICI_WZ_dist_pre_norm =</span> <span class="sc">-</span> <span class="fu">ICI_Norm</span>(W_before_dist, Z_before_dist))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="distributions" class="level3">
<h3 class="anchored" data-anchor-id="distributions">Distributions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>plot_distribution <span class="ot">&lt;-</span> <span class="cf">function</span>(df, x, title) {</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(x))) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"grey40"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">x =</span> <span class="st">"Scores"</span>, <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both, <span class="st">"ICI_YX_rating_pre_norm"</span>, <span class="st">"Pre-Rating ICI_YX"</span>)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both<span class="sc">%&gt;%</span><span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"control"</span>), <span class="st">"ICI_YX_rating_post_norm"</span>, <span class="st">"Post-Rating for Control"</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both<span class="sc">%&gt;%</span><span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"experimental"</span>), <span class="st">"ICI_YX_rating_post_norm"</span>, <span class="st">"Post-Rating for Experiment"</span>)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both, <span class="st">"ICI_YX_dist_pre_norm"</span>, <span class="st">"Pre-distance ICI_YX"</span>)</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both<span class="sc">%&gt;%</span><span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"control"</span>), <span class="st">"ICI_YX_dist_post_norm"</span>, <span class="st">"Post-distance ICI_YX for Control"</span>)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both<span class="sc">%&gt;%</span><span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"experimental"</span>), <span class="st">"ICI_YX_dist_post_norm"</span>, <span class="st">"Post-distance ICI_YX for Experiment"</span>)</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, p5, p6, <span class="at">ncol =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both, <span class="st">"ICI_WZ_rating_pre_norm"</span>, <span class="st">"Pre-Rating ICI_WZ"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(df_prp_both, <span class="st">"ICI_WZ_dist_pre_norm"</span>, <span class="st">"Pre-distance ICI_WZ"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p4, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First plot: Scatter plot of ICI_YX_rating_pre_norm vs ICI_WZ_rating_pre_norm</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_prp_both, <span class="fu">aes</span>(<span class="at">x =</span> ICI_YX_rating_pre_norm, <span class="at">y =</span> ICI_WZ_rating_pre_norm)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot of ICI_YX vs ICI_WZ Ratings"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"ICI_YX Rating"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"ICI_WZ Rating"</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Second plot: Scatter plot of ICI_YX_dist_pre_norm vs ICI_WZ_dist_pre_norm</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_prp_both, <span class="fu">aes</span>(<span class="at">x =</span> ICI_YX_dist_pre_norm, <span class="at">y =</span> ICI_WZ_dist_pre_norm)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot of ICI_YX vs ICI_WZ Distances"</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"ICI_YX Distance"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"ICI_WZ Distance"</span>) <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot accumulated probability distribution group by stimulus type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>plot_accumulated_density <span class="ot">&lt;-</span> <span class="cf">function</span>(df, x, color, title) {</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(x), <span class="at">color =</span> <span class="sc">!!</span><span class="fu">sym</span>(color))) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_ecdf</span>(<span class="at">geom =</span> <span class="st">"step"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">x =</span> <span class="st">"Scores"</span>, <span class="at">y =</span> <span class="st">"Cumulative Probability"</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>plot_density <span class="ot">&lt;-</span> <span class="cf">function</span>(df, x, color, title) {</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(x), <span class="at">color =</span> <span class="sc">!!</span><span class="fu">sym</span>(color))) <span class="sc">+</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..count..), <span class="at">fill =</span> <span class="st">"grey40"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#stat_ecdf(geom = "step", size = 1) +  </span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">x =</span> <span class="st">"Scores"</span>, <span class="at">y =</span> <span class="st">"Cumulative Probability"</span>) <span class="sc">+</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p)</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_density</span>(df_prp_both, <span class="st">"ICI_YX_rating_pre_norm"</span>, <span class="st">"stimulus_type_X_Y"</span>, <span class="st">"Density</span><span class="sc">\n</span><span class="st"> of Pre-Rating"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">plot_density</span>(df_prp_both, <span class="st">"ICI_YX_dist_pre_norm"</span>, <span class="st">"stimulus_type_X_Y"</span>, <span class="st">"Density </span><span class="sc">\n</span><span class="st"> of Pre-Distance"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_accumulated_density</span>(df_prp_both, <span class="st">"ICI_YX_rating_pre_norm"</span>, <span class="st">"stimulus_type_X_Y"</span>, <span class="st">"Cumulative Density</span><span class="sc">\n</span><span class="st"> of Pre-Rating"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">plot_accumulated_density</span>(df_prp_both, <span class="st">"ICI_YX_dist_pre_norm"</span>, <span class="st">"stimulus_type_X_Y"</span>, <span class="st">"Cumulative Density </span><span class="sc">\n</span><span class="st"> of Pre-Distance"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_density</span>(df_prp_both, <span class="st">"ICI_YX_rating_pre_norm"</span>, <span class="st">"stimulus_X_Y"</span>, <span class="st">"Density of Pre-Rating"</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, <span class="at">ncol=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_density</span>(df_prp_both, <span class="st">"ICI_YX_dist_pre_norm"</span>, <span class="st">"stimulus_X_Y"</span>, <span class="st">"Density of Pre-Distance"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, <span class="at">ncol=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_accumulated_density</span>(df_prp_both, <span class="st">"ICI_YX_rating_pre_norm"</span>, <span class="st">"stimulus_X_Y"</span>, <span class="st">"Cumulative Density of Pre-Rating"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, <span class="at">ncol=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot_accumulated_density</span>(df_prp_both, <span class="st">"ICI_YX_dist_pre_norm"</span>, <span class="st">"stimulus_X_Y"</span>, <span class="st">"Cumulative Density of Pre-Distance"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, <span class="at">ncol=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(df_prp_both<span class="sc">$</span>ICI_YX_rating_pre_norm <span class="sc">~</span> df_prp_both<span class="sc">$</span>stimulus_type_X_Y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               Df Sum Sq Mean Sq F value Pr(&gt;F)
df_prp_both$stimulus_type_X_Y   1   0.05 0.04751   0.358   0.55
Residuals                     313  41.48 0.13254               </code></pre>
</div>
</div>
</section>
<section id="normality-test" class="level3">
<h3 class="anchored" data-anchor-id="normality-test">Normality test</h3>
<p>Test for normality using Shapiro-Wilk Test for each index. They seems normal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_prp_both<span class="sc">$</span>ICI_YX_rating_pre_norm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df_prp_both$ICI_YX_rating_pre_norm
W = 0.97394, p-value = 1.777e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_prp_both<span class="sc">$</span>ICI_YX_dist_pre_norm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df_prp_both$ICI_YX_dist_pre_norm
W = 0.9726, p-value = 1.056e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_prp_both<span class="sc">$</span>ICI_YX_rating_post_norm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df_prp_both$ICI_YX_rating_post_norm
W = 0.93783, p-value = 3.192e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_prp_both<span class="sc">$</span>ICI_YX_dist_post_norm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df_prp_both$ICI_YX_dist_post_norm
W = 0.88533, p-value = 1.257e-14</code></pre>
</div>
</div>
</section>
<section id="correlations" class="level3">
<h3 class="anchored" data-anchor-id="correlations">Correlations</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>df_shorted_name <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rating_pre =</span> ICI_YX_rating_pre_norm,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">rating_post =</span> ICI_YX_rating_post_norm,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">distance_pre =</span> ICI_YX_dist_pre_norm,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">distance_post =</span> ICI_YX_dist_post_norm)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>selected_columns <span class="ot">&lt;-</span> df_shorted_name[, <span class="fu">c</span>(<span class="st">'anxiety'</span>, <span class="st">'stress'</span>, <span class="st">'depression'</span>, <span class="st">'Sex_0'</span>, <span class="st">'age'</span>, <span class="st">'rating_pre'</span>, <span class="st">'rating_post'</span>, <span class="st">'distance_pre'</span>, <span class="st">'distance_post'</span>)]</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(selected_columns, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>cor_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  anxiety      stress  depression        Sex_0         age
anxiety        1.00000000  0.84290961  0.84950350  0.013009678 -0.19038253
stress         0.84290961  1.00000000  0.85358218  0.077319077 -0.22205455
depression     0.84950350  0.85358218  1.00000000  0.083863705 -0.18094134
Sex_0          0.01300968  0.07731908  0.08386371  1.000000000  0.07366257
age           -0.19038253 -0.22205455 -0.18094134  0.073662574  1.00000000
rating_pre    -0.07560735 -0.07443259 -0.06005502  0.049078888  0.04878348
rating_post   -0.03295682 -0.02751596 -0.02375800 -0.004242396 -0.08268928
distance_pre  -0.10107376 -0.11389789 -0.09086615  0.072636159  0.04887542
distance_post -0.03164209 -0.02601200 -0.02175057 -0.075899821 -0.12185594
               rating_pre  rating_post distance_pre distance_post
anxiety       -0.07560735 -0.032956823  -0.10107376   -0.03164209
stress        -0.07443259 -0.027515956  -0.11389789   -0.02601200
depression    -0.06005502 -0.023758000  -0.09086615   -0.02175057
Sex_0          0.04907889 -0.004242396   0.07263616   -0.07589982
age            0.04878348 -0.082689278   0.04887542   -0.12185594
rating_pre     1.00000000  0.309718470   0.55006694    0.29041970
rating_post    0.30971847  1.000000000   0.33540380    0.59092254
distance_pre   0.55006694  0.335403797   1.00000000    0.31594470
distance_post  0.29041970  0.590922542   0.31594470    1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the heatmap using corrplot</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>, </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="at">number.cex =</span> <span class="fl">0.7</span>, <span class="at">col =</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"white"</span>, <span class="st">"red"</span>))(<span class="dv">200</span>),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Correlation Heatmap"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Calculate p-values for the correlation matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">names</span>(selected_columns)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(vars)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>p_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, n, n)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(p_matrix) <span class="ot">&lt;-</span> <span class="fu">rownames</span>(p_matrix) <span class="ot">&lt;-</span> vars</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(selected_columns[[i]], selected_columns[[j]], <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>    p_matrix[i, j] <span class="ot">&lt;-</span> test<span class="sc">$</span>p.value</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>p_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   anxiety       stress   depression     Sex_0          age
anxiety       0.000000e+00 2.994172e-86 6.326143e-89 0.8180990 6.821868e-04
stress        2.994172e-86 0.000000e+00 1.206063e-90 0.1710393 7.033532e-05
depression    6.326143e-89 1.206063e-90 0.000000e+00 0.1375086 1.258470e-03
Sex_0         8.180990e-01 1.710393e-01 1.375086e-01 0.0000000 1.922487e-01
age           6.821868e-04 7.033532e-05 1.258470e-03 0.1922487 0.000000e+00
rating_pre    1.807403e-01 1.876295e-01 2.879666e-01 0.3853263 3.881965e-01
rating_post   5.600559e-01 6.266053e-01 6.744521e-01 0.9402179 1.431220e-01
distance_pre  7.323881e-02 4.338042e-02 1.074777e-01 0.1985346 3.873018e-01
distance_post 5.758213e-01 6.455810e-01 7.005745e-01 0.1790546 3.060322e-02
                rating_pre  rating_post distance_pre distance_post
anxiety       1.807403e-01 5.600559e-01 7.323881e-02  5.758213e-01
stress        1.876295e-01 6.266053e-01 4.338042e-02  6.455810e-01
depression    2.879666e-01 6.744521e-01 1.074777e-01  7.005745e-01
Sex_0         3.853263e-01 9.402179e-01 1.985346e-01  1.790546e-01
age           3.881965e-01 1.431220e-01 3.873018e-01  3.060322e-02
rating_pre    0.000000e+00 1.980002e-08 2.616836e-26  1.541963e-07
rating_post   1.980002e-08 0.000000e+00 1.015451e-09  4.846184e-31
distance_pre  2.616836e-26 1.015451e-09 0.000000e+00  9.886029e-09
distance_post 1.541963e-07 4.846184e-31 9.886029e-09  0.000000e+00</code></pre>
</div>
</div>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p><strong>Correlation with Rating (Pre-manipulation)</strong> Anxiety was not significantly correlated with participants’ pre-manipulation ratings, r(315) = -0.08, p = .18.</p>
<p>Stress was not significantly correlated with pre-manipulation ratings, r = -0.07, p = .19.</p>
<p>Depression was not significantly correlated with pre-manipulation ratings, r = -0.06, p = .29.</p>
<p>Sex (coded as 0) was not significantly correlated with pre-manipulation ratings, r = 0.05, p = .39.</p>
<p>Age was not significantly correlated with pre-manipulation ratings, r = 0.05, p = .39.</p>
<p><strong>Correlation with Distance (Pre-manipulation)</strong> Anxiety was marginally negatively correlated with distance to the object, r = -0.10, p = .07.</p>
<p>Stress was significantly negatively correlated with distance, r = -0.11, p = .04.</p>
<p>Depression was not significantly correlated with distance, r = -0.09, p = .11.</p>
<p>Sex was not significantly correlated with distance, r = 0.07, p = .20.</p>
<p>Age was not significantly correlated with distance, r = 0.05, p = .39.</p>
</section>
</section>
<section id="assign-styles" class="level3">
<h3 class="anchored" data-anchor-id="assign-styles">Assign styles</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the SD for Pre and define participants' styles</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>rating_quantile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df_prp_both<span class="sc">$</span>ICI_YX_rating_pre_norm, <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>dist_quantile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df_prp_both<span class="sc">$</span>ICI_YX_dist_pre_norm, <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>))</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="co"># rating</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">sd_pre_rating =</span> <span class="fu">sd</span>(ICI_YX_rating_pre_norm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mean_pre_rating =</span> <span class="fu">mean</span>(ICI_YX_rating_pre_norm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">style_rating =</span> <span class="fu">case_when</span>(</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>           <span class="co">#ICI_YX_rating_pre_norm &gt; mean_pre_rating + sd_pre_rating ~ "Competitive",</span></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>           <span class="co">#ICI_YX_rating_pre_norm &lt; mean_pre_rating - sd_pre_rating ~ "Facilitative",</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>           ICI_YX_rating_pre_norm <span class="sc">&gt;</span> rating_quantile[<span class="dv">2</span>] <span class="sc">~</span> <span class="st">"Competitive"</span>,</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>           ICI_YX_rating_pre_norm <span class="sc">&lt;</span> rating_quantile[<span class="dv">1</span>] <span class="sc">~</span> <span class="st">"Facilitative"</span>,</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">.default =</span> <span class="st">"No-Difference"</span></span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a>         ),</span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a>         <span class="co"># distance</span></span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">sd_pre_distance =</span> <span class="fu">sd</span>(ICI_YX_dist_pre_norm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">mean_pre_distance =</span> <span class="fu">mean</span>(ICI_YX_dist_pre_norm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">style_distance =</span> <span class="fu">case_when</span>(</span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a>           <span class="co">#ICI_YX_dist_pre_norm &gt; mean_pre_distance + sd_pre_distance ~ "Competitive",</span></span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a>           <span class="co">#ICI_YX_dist_pre_norm &lt; mean_pre_distance - sd_pre_distance ~ "Facilitative",</span></span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a>           ICI_YX_dist_pre_norm <span class="sc">&gt;</span> dist_quantile[<span class="dv">2</span>] <span class="sc">~</span> <span class="st">"Competitive"</span>,</span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a>           ICI_YX_dist_pre_norm <span class="sc">&lt;</span> dist_quantile[<span class="dv">1</span>] <span class="sc">~</span> <span class="st">"Facilitative"</span>,</span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">.default =</span> <span class="st">"No-Difference"</span></span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a>         ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>How many participants in each style?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(style_rating) <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(subjectID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  style_rating      n
  &lt;chr&gt;         &lt;int&gt;
1 Competitive     105
2 Facilitative    105
3 No-Difference   105</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(style_distance) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(subjectID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  style_distance     n
  &lt;chr&gt;          &lt;int&gt;
1 Competitive      105
2 Facilitative     105
3 No-Difference    105</code></pre>
</div>
</div>
</section>
<section id="one-way-anova-test-for-normalized-pre-manipulation-ratings" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova-test-for-normalized-pre-manipulation-ratings">One-way ANOVA test for normalized pre-manipulation ratings</h3>
<p>Check assumptions: normality &amp; homogeneity of variances</p>
<ol type="1">
<li>Shapiro-Wilk (normality within each group)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(df_prp_both<span class="sc">$</span>ICI_YX_rating_pre_norm, df_prp_both<span class="sc">$</span>style_rating, shapiro.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df_prp_both$style_rating: Competitive

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.83727, p-value = 2.189e-09

------------------------------------------------------------ 
df_prp_both$style_rating: Facilitative

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.88659, p-value = 2.03e-07

------------------------------------------------------------ 
df_prp_both$style_rating: No-Difference

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.94961, p-value = 0.0005534</code></pre>
</div>
</div>
<p>All groups violate the normality assumption, the p-values are all &lt; 0.05.</p>
<ol start="2" type="1">
<li>Levene’s test (homogeneity of variance)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>df_prp_both<span class="sc">$</span>style_rating_factor <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df_prp_both<span class="sc">$</span>style_rating)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(ICI_YX_rating_pre_norm <span class="sc">~</span> style_rating_factor, <span class="at">data =</span> df_prp_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value   Pr(&gt;F)    
group   2  35.761 1.04e-14 ***
      312                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value is &lt; 0.05, indicating that the variances are not equal across groups.</p>
<p>Run one-way ANOVA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(ICI_YX_rating_pre_norm <span class="sc">~</span> style_rating, <span class="at">data =</span> df_prp_both)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
style_rating   2  29.35  14.677     376 &lt;2e-16 ***
Residuals    312  12.18   0.039                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter    | Eta2 |       95% CI
----------------------------------
style_rating | 0.71 | [0.67, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>A one-way between-subjects ANOVA was conducted to examine the effect of rating style (Competitive, Facilitative, No-Difference) on participants’ normalized pre-manipulation ratings index. The results revealed a statistically significant effect of rating style on normalized rating indexes, F(2, 312) = 376.00, p &lt; .001. The effect size was large, η² = .71, 95% CI [.67, 1.00], indicating that approximately 71% of the variance in normalized pre-manipulation rating indexes can be attributed to rating style.</p>
</section>
<section id="one-way-anova-test-for-normalized-pre-manipulation-distance" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova-test-for-normalized-pre-manipulation-distance">One-way ANOVA test for normalized pre-manipulation distance</h3>
<p>Check assumptions: normality &amp; homogeneity of variances</p>
<ol type="1">
<li>Shapiro-Wilk (normality within each group)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(df_prp_both<span class="sc">$</span>ICI_YX_dist_pre_norm, df_prp_both<span class="sc">$</span>style_distance, shapiro.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df_prp_both$style_distance: Competitive

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.90653, p-value = 1.776e-06

------------------------------------------------------------ 
df_prp_both$style_distance: Facilitative

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.86961, p-value = 3.798e-08

------------------------------------------------------------ 
df_prp_both$style_distance: No-Difference

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.96824, p-value = 0.0127</code></pre>
</div>
</div>
<p>All groups violate the normality assumption, the p-values are all &lt; 0.05.</p>
<ol start="2" type="1">
<li>Levene’s test (homogeneity of variance)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>df_prp_both<span class="sc">$</span>style_distance_factor <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df_prp_both<span class="sc">$</span>style_distance)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(ICI_YX_dist_pre_norm <span class="sc">~</span> style_distance_factor, <span class="at">data =</span> df_prp_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value    Pr(&gt;F)    
group   2  38.645 1.013e-15 ***
      312                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value is &lt; 0.05, indicating that the variances are not equal across groups.</p>
<p>Run one-way ANOVA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(ICI_YX_dist_pre_norm <span class="sc">~</span> style_distance, <span class="at">data =</span> df_prp_both)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq F value Pr(&gt;F)    
style_distance   2 19.929   9.964   359.3 &lt;2e-16 ***
Residuals      312  8.652   0.028                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(anova_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter      | Eta2 |       95% CI
------------------------------------
style_distance | 0.70 | [0.66, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>A one-way between-subjects ANOVA was conducted to examine the effect of distance style (Competitive, Facilitative, No-Difference) on participants’ normalized pre-manipulation distance index. The results revealed a statistically significant effect of distance style on distance indexes, F(2, 312) = 359.3, p &lt; .001. The effect size was large, η² = .70, 95% CI [.66, 1.00], indicating that approximately 71% of the variance in normalized pre-manipulation distance index can be attributed to distance style.</p>
</section>
<section id="two-way-anova-test-for-normalized-post-manipulation-ratings" class="level3">
<h3 class="anchored" data-anchor-id="two-way-anova-test-for-normalized-post-manipulation-ratings">Two-way ANOVA test for normalized post-manipulation ratings</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rating_change =</span> ICI_YX_rating_post_norm <span class="sc">-</span> ICI_YX_rating_pre_norm)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>anova_change <span class="ot">&lt;-</span> <span class="fu">aov</span>(rating_change <span class="sc">~</span> style_rating <span class="sc">*</span> group, <span class="at">data =</span> df_prp_both)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_change)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value Pr(&gt;F)    
style_rating         2  13.23   6.616  49.282 &lt;2e-16 ***
group                1   0.00   0.004   0.032 0.8590    
style_rating:group   2   0.88   0.442   3.295 0.0384 *  
Residuals          309  41.48   0.134                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A two-way between-subjects ANOVA was conducted to examine the effects of rating style (Competitive, Facilitative, No-Difference) and group (Control, Experimental) on the change in normalized rating indexes from pre- to post-manipulation.</p>
<p>There was a significant main effect of rating style, F(2, 309) = 49.28, p &lt; .001, η² = .24, indicating that the amount of change differed significantly across rating styles.</p>
<p>There was no significant main effect of group, F(1, 309) = 0.03, p = .859, suggesting that, overall, control and experimental groups did not differ in change scores.</p>
<p>However, there was a significant interaction between rating styles and group, F(2, 309) = 3.30, p = .038, indicating that the effect of group on rating index change varied depending on the rating style.</p>
</section>
<section id="two-way-anova-test-for-normalized-post-manipulation-distance" class="level3">
<h3 class="anchored" data-anchor-id="two-way-anova-test-for-normalized-post-manipulation-distance">Two-way ANOVA test for normalized post-manipulation distance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>df_prp_both <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dist_change =</span> ICI_YX_dist_post_norm <span class="sc">-</span> ICI_YX_dist_pre_norm)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>anova_change <span class="ot">&lt;-</span> <span class="fu">aov</span>(dist_change <span class="sc">~</span> style_distance <span class="sc">*</span> group, <span class="at">data =</span> df_prp_both)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_change)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value Pr(&gt;F)    
style_distance         2 10.558   5.279  72.953 &lt;2e-16 ***
group                  1  0.027   0.027   0.380 0.5382    
style_distance:group   2  0.365   0.183   2.523 0.0819 .  
Residuals            309 22.359   0.072                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A two-way between-subjects ANOVA was conducted to examine the effects of distance style (Competitive, Facilitative, No-Difference) and group (Control, Experimental) on participants’ normalized distance index.</p>
<p>There was a significant main effect of distance style, F(2, 309) = 72.95, p &lt; .001, η² = .32, indicating that average distance index significantly differed across styles.</p>
<p>There was no significant main effect of group, F(1, 309) = 0.38, p = .538, suggesting that control and experimental groups did not differ overall in distance index.</p>
<p>The interaction between distance style and group was marginally significant, F(2, 309) = 2.52, p = .082, η² ≈ .01, indicating a potential trend that the effect of group may differ depending on distance style, though this did not reach conventional levels of statistical significance.</p>
</section>
</section>
<section id="plot-for-interactions" class="level2">
<h2 class="anchored" data-anchor-id="plot-for-interactions">Plot for Interactions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a function to plot ICI</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>plot_ICI <span class="ot">&lt;-</span> <span class="cf">function</span>(df, pre, post, style, title) {</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Classify based on the `pre` column</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  df_style <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">style =</span> .data[[style]])</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># df_style &lt;- df_style %&gt;% filter(style != 'No-Difference')</span></span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Reshape the data</span></span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>  df_melted <span class="ot">&lt;-</span> df_style <span class="sc">%&gt;%</span></span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(pre, post, <span class="st">'group'</span>, <span class="st">'style'</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(<span class="fu">c</span>(pre, post)), <span class="at">names_to =</span> <span class="st">"flip"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb96-13"><a href="#cb96-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">flip =</span> dplyr<span class="sc">::</span><span class="fu">recode</span>(flip, <span class="sc">!!</span><span class="fu">sym</span>(pre) <span class="sc">:</span><span class="er">=</span> <span class="st">"Pre"</span>, <span class="sc">!!</span><span class="fu">sym</span>(post) <span class="sc">:</span><span class="er">=</span> <span class="st">"Post"</span>))</span>
<span id="cb96-14"><a href="#cb96-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb96-15"><a href="#cb96-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Order the levels</span></span>
<span id="cb96-16"><a href="#cb96-16" aria-hidden="true" tabindex="-1"></a>  df_melted<span class="sc">$</span>flip <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_melted<span class="sc">$</span>flip, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Pre"</span>, <span class="st">"Post"</span>))</span>
<span id="cb96-17"><a href="#cb96-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-18"><a href="#cb96-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Summarize the data to calculate mean and 68% confidence interval</span></span>
<span id="cb96-19"><a href="#cb96-19" aria-hidden="true" tabindex="-1"></a>  df_summary <span class="ot">&lt;-</span> df_melted <span class="sc">%&gt;%</span></span>
<span id="cb96-20"><a href="#cb96-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(group, style, flip) <span class="sc">%&gt;%</span></span>
<span id="cb96-21"><a href="#cb96-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb96-22"><a href="#cb96-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean_value =</span> <span class="fu">mean</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb96-23"><a href="#cb96-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">se =</span> <span class="fu">sd</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>()), </span>
<span id="cb96-24"><a href="#cb96-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">ci_68 =</span> se <span class="sc">*</span> <span class="fu">qnorm</span>(<span class="fl">0.84</span>),   <span class="co"># Approx 68% CI (1 standard error)</span></span>
<span id="cb96-25"><a href="#cb96-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb96-26"><a href="#cb96-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb96-27"><a href="#cb96-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb96-28"><a href="#cb96-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot using ggplot2 with error bars</span></span>
<span id="cb96-29"><a href="#cb96-29" aria-hidden="true" tabindex="-1"></a>  g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_summary, <span class="fu">aes</span>(<span class="at">x =</span> flip, <span class="at">y =</span> mean_value, <span class="at">color =</span> group, <span class="at">group =</span> group)) <span class="sc">+</span></span>
<span id="cb96-30"><a href="#cb96-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span>  <span class="co"># Increase point size</span></span>
<span id="cb96-31"><a href="#cb96-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Use linewidth for the main lines</span></span>
<span id="cb96-32"><a href="#cb96-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_value <span class="sc">-</span> ci_68, <span class="at">ymax =</span> mean_value <span class="sc">+</span> ci_68), <span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">linewidth =</span> .<span class="dv">8</span>) <span class="sc">+</span>  <span class="co"># Error bars with thinner lines</span></span>
<span id="cb96-33"><a href="#cb96-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>style, <span class="at">scales =</span> <span class="st">"fixed"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Use "fixed" for shared y-axis</span></span>
<span id="cb96-34"><a href="#cb96-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">y =</span> <span class="st">"ICI"</span>, <span class="at">x =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb96-35"><a href="#cb96-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb96-36"><a href="#cb96-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb96-37"><a href="#cb96-37" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">"bold"</span>),  <span class="co"># Adjust title size</span></span>
<span id="cb96-38"><a href="#cb96-38" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),  <span class="co"># Axis title size</span></span>
<span id="cb96-39"><a href="#cb96-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),   <span class="co"># Axis text size</span></span>
<span id="cb96-40"><a href="#cb96-40" aria-hidden="true" tabindex="-1"></a>      <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),  <span class="co"># Facet title size</span></span>
<span id="cb96-41"><a href="#cb96-41" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb96-42"><a href="#cb96-42" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),  <span class="co"># Adjust legend text size</span></span>
<span id="cb96-43"><a href="#cb96-43" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),  <span class="co"># Remove major vertical grid lines</span></span>
<span id="cb96-44"><a href="#cb96-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),  <span class="co"># Remove minor vertical grid lines</span></span>
<span id="cb96-45"><a href="#cb96-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>, <span class="at">linewidth =</span> <span class="fl">0.1</span>),  <span class="co"># Add major horizontal grid lines</span></span>
<span id="cb96-46"><a href="#cb96-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),  <span class="co"># Remove minor horizontal grid lines</span></span>
<span id="cb96-47"><a href="#cb96-47" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.spacing =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">"lines"</span>),  <span class="co"># Tighten space between panels</span></span>
<span id="cb96-48"><a href="#cb96-48" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.line.x =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"black"</span>),  <span class="co"># Add x-axis line</span></span>
<span id="cb96-49"><a href="#cb96-49" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.line.y.left =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"black"</span>)  <span class="co"># Left y-axis</span></span>
<span id="cb96-50"><a href="#cb96-50" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb96-51"><a href="#cb96-51" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"orange"</span>)) </span>
<span id="cb96-52"><a href="#cb96-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-53"><a href="#cb96-53" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Display the plot</span></span>
<span id="cb96-54"><a href="#cb96-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(g)</span>
<span id="cb96-55"><a href="#cb96-55" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb96-56"><a href="#cb96-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-57"><a href="#cb96-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage</span></span>
<span id="cb96-58"><a href="#cb96-58" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ICI</span>(df_prp_both, <span class="st">'ICI_YX_rating_pre_norm'</span>, <span class="st">'ICI_YX_rating_post_norm'</span>, <span class="st">'style_rating'</span>, <span class="st">'Normalized ICI-YX Ratings'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ICI</span>(df_prp_both, <span class="st">'ICI_YX_dist_pre_norm'</span>, <span class="st">'ICI_YX_dist_post_norm'</span>, <span class="st">'style_distance'</span>, <span class="st">'Normalized ICI-YX Distances'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-43-2.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="convert-data-to-a-long-format" class="level2">
<h2 class="anchored" data-anchor-id="convert-data-to-a-long-format">Convert data to a long format</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>df_prp_long <span class="ot">&lt;-</span> df_prp_both <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subjectID, group, style_rating, style_distance, ICI_YX_rating_pre_norm, ICI_YX_rating_post_norm, ICI_YX_dist_pre_norm, ICI_YX_dist_post_norm) <span class="sc">%&gt;%</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(ICI_YX_rating_pre_norm, ICI_YX_rating_post_norm, ICI_YX_dist_pre_norm, ICI_YX_dist_post_norm), <span class="at">names_to =</span> <span class="st">"Index"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) </span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co"># save to CSV</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(df_prp_long, <span class="st">"./exp4-ICI.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
</section>
<section id="references" class="level1">
<h1>References</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>